api = "0.2"

[buildpack]
id = "com.anynines.buildpacks.rvm"
name = "RVM Buildpack"
version = "0.0.7"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "heroku-18"
